#!/usr/bin/env -S deno run --allow-all

let exitCode = 0;

const lint = await new Deno.Command('npm', {
  args: ['run', 'lint'],
  stdout: 'piped',
  stderr: 'piped',
  env: {
    ...Deno.env.toObject(),
    FORCE_COLOR: '1',
  },
}).output();
if (lint.code !== 0) {
  console.error('Lint failed');
  await Deno.stdout.write(lint.stderr);
  exitCode = 1;
}

const tsc = await new Deno.Command('tsc', {
  args: ['--project', 'tsconfig.json', '--noEmit'],
  stdout: 'piped',
  stderr: 'piped',
  env: {
    ...Deno.env.toObject(),
  },
}).output();
if (tsc.code !== 0) {
  console.error('TypeScript check failed');
  await Deno.stdout.write(tsc.stdout);
  exitCode = 1;
}

if (exitCode === 0) {
  console.log('All checks passed');
}
Deno.exit(exitCode);
